### ISSUE TITLE
CUDA out of memory [Google collab]

### ISSUE THREAD

**Issue by Rishabhg71** [huggingface/autotrain-advanced#250]
I am already using Google Collab as mentioned in #177 but I am still getting this error, I am using DreamBooth Training (AutoTrain_Dreambooth.ipynb). I have programming experience but this is my first time doing anything related to PyTorch. So any help is appreciated 

```
Loading pipeline components...: 100%
7/7 [01:34<00:00, 12.77s/it]
Loading pipeline components...: 100%
5/5 [01:20<00:00, 19.05s/it]
100%
50/50 [00:45<00:00, 1.20it/s]
---------------------------------------------------------------------------
OutOfMemoryError                          Traceback (most recent call last)
[<ipython-input-1-c6ea84cff8f6>](https://localhost:8080/#) in <cell line: 29>()
     27 seed = 42
     28 generator = torch.Generator("cuda").manual_seed(seed)
---> 29 image = pipe(prompt=prompt, generator=generator).images[0]
     30 image = refiner(prompt=prompt, generator=generator, image=image).images[0]
     31 image.save(f"generated_image.png")

11 frames
[/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py](https://localhost:8080/#) in interpolate(input, size, scale_factor, mode, align_corners, recompute_scale_factor, antialias)
   3929         return torch._C._nn.upsample_nearest1d(input, output_size, scale_factors)
   3930     if input.dim() == 4 and mode == "nearest":
-> 3931         return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
   3932     if input.dim() == 5 and mode == "nearest":
   3933         return torch._C._nn.upsample_nearest3d(input, output_size, scale_factors)

OutOfMemoryError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 14.75 GiB total capacity; 12.70 GiB already allocated; 488.81 MiB free; 12.96 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by sankeerth-bussa** [comment]
I am also getting same error. Even tried a AWS EC2 instance with more GPU than available in Google Colab, still the error is same. Doing troubleshooting I removed the refiner code and ran it generated the imaged but not so good. I think the refiner has to be modified but I am stuck.

**Comment by sankeerth-bussa** [comment]
@RG7279805  I got solution posted in this issue, pls check

#252

**Comment by RG7279805** [comment]
Thanks for helping man @sankeerth-bussa

**Comment by RG7279805** [comment]
@sankeerth-bussa I haven't got the chance to test it but will post it soon

**Comment by saurabhbidwai** [comment]
@RG7279805  it didn't help me
![image](https://github.com/huggingface/autotrain-advanced/assets/22415674/eb39339a-6e16-4cec-bd97-1ab502205a64)

**Comment by RG7279805** [comment]
@saurabhbidwai @sankeerth-bussa  https://github.com/huggingface/autotrain-advanced/issues/252#issuecomment-1707058262 is working for me
