### ISSUE TITLE
H100 Compatibility - PyTorch Issues

### ISSUE THREAD

**Issue by mathis-lambert** [huggingface/autotrain-advanced#281]
Hi, 

I might be on the wrong place but, this kind of issues has already been raised on PyTorch repo so i'm trying here.

## Context
I want to fine-tune Llama2-70B-chat-hf with any dataset on an Nvidia H100 instance running with CUDA 12.2 v2. To fine-tune it, i chose autotrain-advanced with Python 3.10.

## First try
For the first try, i've simply made a venv and installed autotrain-advanced,
then run :
```bash
$ - autotrain setup
```
So far, everything has gone successfully...
After that, i'm running my train command :
```bash 
$ - autotrain llm --train --project_name test_llm --model meta-llama/Llama-2-70b-chat-hf --data_path knowrohit07/know_sql  --use_peft --trainer sft --learning_rate 2e-4  --use_int4 --train_batch_size 24 --token [my_token]
```
And then, i've got this error :
```bash
/scratch/torchbuild/lib/python3.10/site-packages/torch/cuda/__init__.py:173: UserWarning:
**NVIDIA H100 PCIe with CUDA capability sm_90 is not compatible with the current PyTorch installation.**
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75 sm_80 sm_86.
If you want to use the NVIDIA H100 PCIe GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
```
### What i tried to handle it
I tried so many things to handle this PyTorch issue : 
- Install older CUDA Driver : 22.1 (which is supported by the latest PyTorch Nightly version)
- Build PyTorch from source in a venv as it is suggested following the PyTorch's repo process
- Build with and without conda/mkl
- Build on different CUDA Versions

### Conclusion
Always this same warning saying me that the PyTorch version isn't compatible for sm_90 capabilities (H100).
And ... as reported by ML Engineer at Nvidia :
https://github.com/pytorch/pytorch/issues/90761#issuecomment-1673709633
![image](https://github.com/huggingface/autotrain-advanced/assets/93223257/ef80599e-aa2a-4db9-8162-0fb6d6957124)

I'm gonna post this also on the PyTorch repo but if someone got the same issue, and fixed it, i won't say no to a little help.

If you need deeper context, let me know and i'll provide it.

Many thanks.

**Comment by abhishekkrthakur** [comment]
Does the dockerfile work or still the same error?

**Comment by mathis-lambert** [comment]
@abhishekkrthakur I'll try asap, and i will keep you in touch. 
Thanks

**Comment by mathis-lambert** [comment]
Okay, here's what have worked for me to use H100 Gpu capabilities :
- export TORCH_CUDA_ARCH_LIST="9.0"
- Build Magma from source :
```bash
git clone --single-branch --branch v2.7.1 --depth 1 https://bitbucket.org/icl/magma.git
cd magma

echo -e "GPU_TARGET = sm_86\nBACKEND = cuda\nFORT = false" > make.inc
make generate

export LD_LIBRARY_PATH="${CONDA_PREFIX}/lib:/usr/local/cuda/targets/x86_64-linux/lib${LD_LIBRARY_PATH:+${LD_LIBRARY_PATH}:}"
export CUDA_DIR="/usr/local/cuda/12.2"
export CONDA_LIB=${CONDA_PREFIX}/lib

# be careful here; they didn't accept sm_89 so I had to round it down to major version, sm_80
make clean && rm -rf build/

TARGETARCH=amd64 cmake -H. -Bbuild -DUSE_FORTRAN=OFF -DGPU_TARGET="Ampere" -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON -DCMAKE_CXX_FLAGS="-fPIC" -DCMAKE_C_FLAGS="-fPIC" -DMKLROOT=${CONDA_PREFIX} -DCUDA_NVCC_FLAGS="-Xfatbin;-compress-all;-DHAVE_CUBLAS;-std=c++11;--threads=0;" -GNinja 

sudo mkdir /usr/local/magma/

sudo cmake --build build -j $(nproc) --target install

sudo cp build/include/* /usr/local/magma/include/
sudo cp build/lib/*.so /usr/local/magma/lib/
sudo cp build/lib/*.a /usr/local/magma/lib/
sudo cp build/lib/pkgconfig/*.pc /usr/local/magma/lib/pkgconfig/
sudo cp /usr/local/magma/include/* ${CONDA_PREFIX}/include/
sudo cp /usr/local/magma/lib/*.a ${CONDA_PREFIX}/lib/
sudo cp /usr/local/magma/lib/*.so ${CONDA_PREFIX}/lib/
sudo cp /usr/local/magma/lib/pkgconfig/*.pc ${CONDA_PREFIX}/lib/pkgconfig/
```
- Build [PyTorch from source](https://github.com/pytorch/pytorch#from-source)
- Build [Xformers from source](https://github.com/facebookresearch/xformers#installing-xformers)
```bash
# (Optional) Makes the build much faster
pip install ninja
# Set TORCH_CUDA_ARCH_LIST if running and building on different GPU types
pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers
# (this can take dozens of minutes)
```

## After that :
verify your installation with :
- pip show torch
- pip show xformers

and check if the version is followed by the git repo.

Then, you can type :
```bash
python -m torch.utils.collect_env
````
and check if the CUDA version used to build torch is the same as your current CUDA Version.

Finally, when after launched :
```bash
autotrain setup
```
(you might reinstall torch & xformers after the setup via pip)

If you have any questions, tell me.
