### ISSUE TITLE
The Youtube Fine tuning tutorial is outdated in the commands.

### ISSUE THREAD

**Issue by venturaEffect** [huggingface/autotrain-advanced#429]
Hi,

I'm trying to fine tune a model from Huggingface, more precisely `ehartford/dolphin-2.1-mistral-7b`.

I'm using an NVIDIA 4090. Tried other ways to fine tune like doing it with custom code using transformers from Hugging Face. No success, I get CUDA out of memory (not clear why because, there isn't anything else working).

Anyway, comming to your repo. I've done everything what it tells. Following your Youtube video for fine tuning, I converted my .json into a csv file and added in the same path. Run the commands you have said. But, first of all the commands are different now. I get some errors, but when I look at the commands there are some that I can't figure out which is now the new one. And in the docs it doesn't explain anything about them.

This is what I have so far:

`autotrain llm --train --project-name the_ai_lawyer --model ehartford/dolphin-2.1-mistral-7b --data . --peft --use_int4 --learning_rate 2e-4 --batch_size 6 --epochs 3 --trainer sft `

But there is clearly still some wrong, at least `--learning-rate` but can't really "discover" which one is by looking at: 

<img width="932" alt="Captura de pantalla 2023-12-21 145638" src="https://github.com/huggingface/autotrain-advanced/assets/29057173/aabab150-dee2-4bf1-acd9-59a31281493a">

Would be cool if the docs explain a bit about the different commands so there is no need to write asking for it.

Appreciate.

**Comment by abhishekkrthakur** [comment]
--lr is learning rate if thats your concern

**Comment by abhishekkrthakur** [comment]
--lr --peft --mixed-precision fp16 --quantization int4

is what you need
there is also a link to colab and you can also run ui locally in case of confusion

**Comment by abhishekkrthakur** [comment]
Use the UI locally:

export HF_TOKEN=your_hf_write_token
export AUTOTRAIN_LOCAL=1

then run: autotrain app

This will train your models locally and store training data locally too

**Comment by venturaEffect** [comment]
> Use the UI locally:
> 
> export HF_TOKEN=your_hf_write_token export AUTOTRAIN_LOCAL=1
> 
> then run: autotrain app
> 
> This will train your models locally and store training data locally too

Appreciate, this would be very useful. But where do I wrtie that? Thanks!

**Comment by abhishekkrthakur** [comment]
terminal

**Comment by venturaEffect** [comment]
Ok, as always even with Auto-train too. There is always problems with bitsandbytes, everywhere people is complaining. Do you have any idea how to solve it with Auto-train?

`❌ ERROR  | 2023-12-21 15:38:27 | autotrain.trainers.common:wrapper:86 - train has failed due to an exception: Traceback (most recent call last):
  File "C:\Users\zaesa\AppData\Roaming\Python\Python310\site-packages\transformers\utils\import_utils.py", line 1382, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\zaesa\AppData\Roaming\Python\Python310\site-packages\transformers\integrations\bitsandbytes.py", line 11, in <module>
    import bitsandbytes as bnb
  File "C:\Users\zaesa\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\__init__.py", line 6, in <module>      
    from . import cuda_setup, utils, research
  File "C:\Users\zaesa\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\zaesa\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\zaesa\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\zaesa\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\zaesa\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\cextension.py", line 20, in <module>   
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\zaesa\AppData\Roaming\Python\Python310\site-packages\autotrain\trainers\common.py", line 83, in wrapper  
    return func(*args, **kwargs)
  File "C:\Users\zaesa\AppData\Roaming\Python\Python310\site-packages\autotrain\trainers\clm\__main__.py", line 157, in train
    model = AutoModelForCausalLM.from_pretrained(
  File "C:\Users\zaesa\AppData\Roaming\Python\Python310\site-packages\transformers\models\auto\auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\zaesa\AppData\Roaming\Python\Python310\site-packages\transformers\modeling_utils.py", line 3464, in from_pretrained
    from .integrations import get_keys_to_not_convert, replace_with_bnb_linear
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\zaesa\AppData\Roaming\Python\Python310\site-packages\transformers\utils\import_utils.py", line 1372, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\zaesa\AppData\Roaming\Python\Python310\site-packages\transformers\utils\import_utils.py", line 1384, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.integrations.bitsandbytes because of the following error (look up to see its traceback):

        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

❌ ERROR  | 2023-12-21 15:38:27 | autotrain.trainers.common:wrapper:87 - Failed to import transformers.integrations.bitsandbytes because of the following error (look up to see its traceback):

        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
`

Appreciate your help.

**Comment by venturaEffect** [comment]
Yes it is already installed. It is a problem with bitsandbytes. 

The repo is full we people complaining all the time about it. Bitsandbytes is a pain in the ass. I've encounter this issue using axolotl, llama.cpp, extensions in VS like Windows AI Studio,...

Alsways the same problem and already for weeks.

It's a bit sad, because at the end nothing really works locally because of bitsandbytes

**Comment by abhishekkrthakur** [comment]
it works for me on a 3090 gpu and also on a titan rtx. so, its probably how you have setup cuda toolkit and nvcc. what you can do is use miniconda3, create a python 3.10 environment, and install cuda-nvcc and toolkit using conda, then install autotrain-advanced.

```
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
./Miniconda3-latest-Linux-x86_64.sh
conda create -n autotrain -y python=3.10
conda activate autotrain
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
conda install -c "nvidia/label/cuda-12.1.0" cuda-nvcc
conda install -c "nvidia/label/cuda-12.1.0" cuda-toolkit
```
try it if you can / want to :)

**Comment by venturaEffect** [comment]
Well, you are using Linux. In Windows 11 bitsandbytes doesn't work properly. Even Tim, the account where is the bitsandbytes repo does affirm that.

So, as Windows users, we always face this problem.

**Comment by abhishekkrthakur** [comment]
then i cannot be of any further help :) sorry

**Comment by abhishekkrthakur** [comment]
how about using WSL2?

**Comment by venturaEffect** [comment]
You are right. I have it already installed will put the folder from autotrain and follow your commands.

Appreciate!

**Comment by venturaEffect** [comment]
One last question.

Is it just possible to fine-tune the models that appear on the auto train UI? If not, how could I fine-tune any other LLM from huggingface?

Appreciate

**Comment by abhishekkrthakur** [comment]
https://github.com/huggingface/autotrain-advanced/issues/418#issuecomment-1864912617
