### ISSUE TITLE
[BUG] Cuda out of memory.

### ISSUE THREAD

**Issue by Miroun** [huggingface/autotrain-advanced#446]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Other cloud providers

### Interface Used

CLI

### CLI Command

autotrain llm --train --project-name testTraining --model microsoft/phi-1_5 --data-path .  --quantization none --lr 2e-4 --batch-size 12 --epochs 1 --trainer sft --disable-gc

### Error Logs

> INFO    Running LLM
> INFO    Params: Namespace(version=False, text_column='text', rejected_text_column='rejected', prompt_text_column='prompt', model_ref=None, warmup_ratio=0.1, optimizer='adamw_torch', scheduler='linear', weight_decay=0.0, max_grad_norm=1.0, add_eos_token=False, block_size=-1, peft=False, lora_r=16, lora_alpha=32, lora_dropout=0.05, logging_steps=-1, evaluation_strategy='epoch', save_total_limit=1, save_strategy='epoch', auto_find_batch_size=False, mixed_precision=None, quantization='none', model_max_length=1024, trainer='sft', target_modules=None, merge_adapter=False, use_flash_attention_2=False, dpo_beta=0.1, apply_chat_template=False, padding=None, train=True, deploy=False, inference=False, username=None, backend='local-cli', token=None, repo_id=None, push_to_hub=False, model='microsoft/phi-1_5', project_name='testTraining', seed=42, epochs=1, gradient_accumulation=1, disable_gradient_checkpointing=True, lr=0.0002, log='none', data_path='.', train_split='train', valid_split=None, batch_size=12, func=<function run_llm_command_factory at 0x7fe28d14e710>)
> INFO    Dataset: testTraining (lm_training)
Train data: ['./train.csv']
Valid data: []
Column mapping: {'text': 'text', 'rejected_text': 'rejected', 'prompt': 'prompt'}

Saving the dataset (1/1 shards): 100%|███████████| 52002/52002 [00:00<00:00, 2903246.46 examples/s]
Saving the dataset (1/1 shards): 100%|███████████| 52002/52002 [00:00<00:00, 3013390.21 examples/s]
> INFO    Starting local training...
> INFO    {"model":"microsoft/phi-1_5","project_name":"testTraining","data_path":"testTraining/autotrain-data","train_split":"train","valid_split":null,"add_eos_token":false,"block_size":-1,"model_max_length":1024,"padding":null,"trainer":"sft","use_flash_attention_2":false,"log":"none","disable_gradient_checkpointing":true,"logging_steps":-1,"evaluation_strategy":"epoch","save_total_limit":1,"save_strategy":"epoch","auto_find_batch_size":false,"mixed_precision":null,"lr":0.0002,"epochs":1,"batch_size":12,"warmup_ratio":0.1,"gradient_accumulation":1,"optimizer":"adamw_torch","scheduler":"linear","weight_decay":0.0,"max_grad_norm":1.0,"seed":42,"apply_chat_template":false,"quantization":"none","target_modules":null,"merge_adapter":false,"peft":false,"lora_r":16,"lora_alpha":32,"lora_dropout":0.05,"model_ref":null,"dpo_beta":0.1,"prompt_text_column":"autotrain_prompt","text_column":"autotrain_text","rejected_text_column":"autotrain_rejected_text","push_to_hub":false,"repo_id":null,"username":null,"token":null}
> INFO    ['accelerate', 'launch', '--num_machines', '1', '--num_processes', '1', '--mixed_precision', 'no', '-m', 'autotrain.trainers.clm', '--training_config', 'testTraining/training_params.json']
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/usr/local/lib/python3.10/dist-packages/trl/trainer/ppo_config.py:141: UserWarning: The `optimize_cuda_cache` arguement will be deprecated soon, please use `optimize_device_cache` instead.
  warnings.warn(
🚀 INFO   | 2023-12-28 22:17:58 | __main__:process_input_data:41 - loading dataset from disk
🚀 INFO   | 2023-12-28 22:17:58 | __main__:process_input_data:82 - Train data: Dataset({
    features: ['autotrain_text'],
    num_rows: 52002
})
🚀 INFO   | 2023-12-28 22:17:58 | __main__:process_input_data:83 - Valid data: None
tokenizer_config.json: 100%|██████████████████████████████████████| 237/237 [00:00<00:00, 1.97MB/s]
vocab.json: 100%|███████████████████████████████████████████████| 798k/798k [00:00<00:00, 65.3MB/s]
merges.txt: 100%|███████████████████████████████████████████████| 456k/456k [00:00<00:00, 62.3MB/s]
tokenizer.json: 100%|█████████████████████████████████████████| 2.11M/2.11M [00:00<00:00, 14.5MB/s]
added_tokens.json: 100%|██████████████████████████████████████| 1.08k/1.08k [00:00<00:00, 6.04MB/s]
special_tokens_map.json: 100%|███████████████████████████████████| 99.0/99.0 [00:00<00:00, 552kB/s]
config.json: 100%|████████████████████████████████████████████████| 732/732 [00:00<00:00, 3.51MB/s]
configuration_phi.py: 100%|███████████████████████████████████| 2.03k/2.03k [00:00<00:00, 14.6MB/s]
A new version of the following files was downloaded from https://huggingface.co/microsoft/phi-1_5:
- configuration_phi.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
modeling_phi.py: 100%|█████████████████████████████████████████| 33.5k/33.5k [00:00<00:00, 104MB/s]
A new version of the following files was downloaded from https://huggingface.co/microsoft/phi-1_5:
- modeling_phi.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
pytorch_model.bin: 100%|███████████████████████████████████████| 2.84G/2.84G [00:13<00:00, 208MB/s]
generation_config.json: 100%|████████████████████████████████████| 69.0/69.0 [00:00<00:00, 545kB/s]
⚠️ WARNING | 2023-12-28 22:18:20 | __main__:train:262 - The chosen tokenizer supports a `model_max_length` that is longer than the default `block_size` value of 1024. If you would like to use a longer `block_size` up to `tokenizer.model_max_length` you can override this default with `--block_size xxx`.
🚀 INFO   | 2023-12-28 22:18:20 | __main__:train:277 - Using block size 1024
🚀 INFO   | 2023-12-28 22:18:20 | __main__:train:339 - creating trainer
  0%|                                                                     | 0/4334 [00:00<?, ?it/s]You're using a CodeGenTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
❌ ERROR  | 2023-12-28 22:18:25 | autotrain.trainers.common:wrapper:90 - train has failed due to an exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/common.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm/__main__.py", line 475, in train
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/trl/trainer/sft_trainer.py", line 280, in train
    output = super().train(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1854, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2728, in training_step
    loss = self.compute_loss(model, inputs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2751, in compute_loss
    outputs = model(**inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/microsoft/phi-1_5/24f9ea14df973a49a0d87c16d04df88d90067468/modeling_phi.py", line 954, in forward
    hidden_states = self.transformer(input_ids, past_key_values=past_key_values, attention_mask=attention_mask)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/microsoft/phi-1_5/24f9ea14df973a49a0d87c16d04df88d90067468/modeling_phi.py", line 916, in forward
    hidden_states = layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/microsoft/phi-1_5/24f9ea14df973a49a0d87c16d04df88d90067468/modeling_phi.py", line 770, in forward
    attn_outputs = self.mixer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/microsoft/phi-1_5/24f9ea14df973a49a0d87c16d04df88d90067468/modeling_phi.py", line 722, in forward
    attn_output = self._forward_self_attn(x, attention_mask)
  File "/root/.cache/huggingface/modules/transformers_modules/microsoft/phi-1_5/24f9ea14df973a49a0d87c16d04df88d90067468/modeling_phi.py", line 621, in _forward_self_attn
    return self.inner_attn(qkv, key_padding_mask=key_padding_mask)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/microsoft/phi-1_5/24f9ea14df973a49a0d87c16d04df88d90067468/modeling_phi.py", line 373, in forward
    scores = scores + rearrange(padding_mask, "b s -> b 1 1 s")
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.50 GiB. GPU 0 has a total capacty of 79.15 GiB of which 41.31 MiB is free. Process 3175799 has 79.10 GiB memory in use. Of the allocated memory 78.31 GiB is allocated by PyTorch, and 303.24 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

❌ ERROR  | 2023-12-28 22:18:25 | autotrain.trainers.common:wrapper:91 - CUDA out of memory. Tried to allocate 1.50 GiB. GPU 0 has a total capacty of 79.15 GiB of which 41.31 MiB is free. Process 3175799 has 79.10 GiB memory in use. Of the allocated memory 78.31 GiB is allocated by PyTorch, and 303.24 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
  0%|                                                                     | 0/4334 [00:02<?, ?it/s]

### Additional Information

Hello,
I am using a cloud service that allows me to open a docker image with Ubuntu (without ui) that comes with GPU (here I used an A100) and I keep getting errors "cuda out of memory". People working in the cloud service is telling me that the error comes from the program.

What should I do ?

**Comment by Miroun** [comment]
I realised I have this error with "microsoft/phi..." but not the casual llama2 presented in your video @abhishekkrthakur.
Any idea why I faced this exactly with this model, is it unsupported and I misread something

**Comment by Miroun** [comment]
Noone can confirm the problem comes from using microsoft/phi

**Comment by RubenFlorissen** [comment]
You need to set the --peft flag when starting the program. Otherwise, I don't think any model runs. Even with a 45 GB VRAM card, I couldn't fine-tune a 3b model without enabling peft.

**Comment by dpasch01** [comment]
I have the same exact issue. And I am using the `--use_peft` flag.

```bash
!autotrain llm --train \
    --project_name "phi-2-finetune" \
    --model "microsoft/phi-2" \
    --data_path ./ \
    --train_split "train" \
    --valid_split "test" \
    --text_column "prompt" \
    --learning_rate 2e-5 \
    --train_batch_size 2 \
    --gradient_accumulation_steps 5 \
    --num_train_epochs 2 \
    --merge_adapter \
    --model_max_length 512 \
    --trainer sft \
    --use_peft \
    --use_int4 \
    --fp16 \
    --optimizer paged_adamw_8bit \
    --add_eos_token \
    --lora_r 16 \
    --lora_alpha 32 \
    --lora_dropout 0.05 \
    --target_modules "q_proj,k_proj,v_proj,dense,fc1,fc2"
```

Any help here?

**Comment by Nadav-Nesher** [comment]
I had the same issue. Upgrading the GPU did the trick.
